### ISSUE TITLE
Import II_GA_IP_CATEGORIES

### ISSUE THREAD

**Issue by tbaxter-18f** [18F/NRM-Grants-Agreements#182] opened 2021-04-09 17:37 UTC
**Background**
Grants are supposed to show and allow editing of Program categories. To do so we will need to import and use another DB table.

**We'll know we're done when...**
- [x] Data is exported from prod data
- [x] data is cleaned as needed
- [x] Model is imported into our DB
- [x] Models are created
- [ ] Data is usable in app
- [ ] follow-up issues are logged if needed

**Tasks**
- [ ] 
- [ ]

**Comment by allisonnorman** [comment] 2021-04-20 19:28
Closing this as it's in the done column but the issue is still open.

**Closed by allisonnorman** 2021-04-20 19:28 UTC
Labels: engineering
